force-app/main/default/objects/personal_info__c/personal_info__c.object-meta.xml
<CustomObject>
    <label>personal_info</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>personal_info_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>personal_infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/personal_info__c/fields/address__c.field-meta.xml
<CustomField>
    <fullName>address__c</fullName>
    <label>address</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/personal_info__c/fields/bio__c.field-meta.xml
<CustomField>
    <fullName>bio__c</fullName>
    <label>bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/personal_info__c/fields/birthday__c.field-meta.xml
<CustomField>
    <fullName>birthday__c</fullName>
    <label>birthday</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/personal_info__c/fields/first_name__c.field-meta.xml
<CustomField>
    <fullName>first_name__c</fullName>
    <label>first_name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/personal_info__c/fields/last_name__c.field-meta.xml
<CustomField>
    <fullName>last_name__c</fullName>
    <label>last_name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/personal_info__c/fields/links__c.field-meta.xml
<CustomField>
    <fullName>links__c</fullName>
    <label>links</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/personal_info__c/fields/phone_number__c.field-meta.xml
<CustomField>
    <fullName>phone_number__c</fullName>
    <label>phone_number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/DataTableLWC.cls
public with sharing class DataTableLWC {

    @AuraEnabled(cacheable = true)
    public static List<personal_info__c> fetchDataList(Integer offsetNum, Integer limitNum){
      List<personal_info__c> listData;
      if (personal_info__c.SObjectType.getDescribe().isAccessible() && 
          Schema.SObjectType.personal_info__c.fields.Id.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.Name.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.first_name__c.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.last_name__c.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.birthday__c.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.address__c.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.email__c.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.phone_number__c.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.bio__c.isAccessible() &&
          Schema.SObjectType.personal_info__c.fields.links__c.isAccessible()
      ) {
        listData = [SELECT Id , 
                          Name, 
                          first_name__c, 
                          last_name__c, 
                          birthday__c, 
                          address__c, 
                          email__c, 
                          phone_number__c, 
                          bio__c,
                          links__c
                          FROM personal_info__c
                          LIMIT :limitNum
                          OFFSET :((offsetNum - 1) * limitNum)];
    }
    return listData;
  }

  @AuraEnabled(cacheable = true)
  public static Integer countRecordOfList(){
    Integer numberDatas = 0;
    if (personal_info__c.SObjectType.getDescribe().isAccessible()){
      numberDatas = [SELECT COUNT() FROM personal_info__c];
    }
    return numberDatas;
  }
}